### ISSUE TITLE
Деплой на GitHub Pages

### ISSUE THREAD

**Issue by ExEr7um** [ExEr7um/exer7um.com#6]
### Путь файла
`.github/workflows/gh-pages.yml`

### Текст файла
```yml
name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          npm install
          npm run generate
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
```
